server:
  port: 9004
spring:
  application:
    name: inventory
  datasource:
    username: 'grupoinmaculada'
    url: jdbc:postgresql://localhost:5432/inventory
    password: 'password'
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: 'true'
