server:
  port: 8082
spring:
  application:
    name: fraud
  datasource:
    username: 'grupoinmaculada'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'password'
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: 'true'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.2.195:8761/eureka
    instance:
      preferIpAddress: true
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health,metrics,prometheus'
  endpoint:
    health:
      enable: true
      show-details: always
    prometheus:
      enabled: true
# docker compose -f stack.yml up
# docker inspect <COINTAINER ID> | grep IPAddress